const textsPickaski = {
    metaDescription: {
        "en": "Discover your perfect ski match with our free and user-friendly tool! Tailored for both beginners and seasoned skiers, our service helps you find the ideal ski model to suit your skill level, style, and terrain preferences. Make your next ski adventure unforgettable with skis that are just right for you. Try it now – effortless, accurate, and absolutely free!",
        "nl": "Ontdek uw perfecte ski-match met onze gratis en gebruiksvriendelijke tool! Op maat gemaakt voor zowel beginners als ervaren skiërs, onze service helpt u het ideale skimodel te vinden dat past bij uw vaardigheidsniveau, stijl en terreinvoorkeuren. Maak uw volgende ski-avontuur onvergetelijk met ski's die precies goed voor u zijn. Probeer het nu - moeiteloos, nauwkeurig en helemaal gratis!",
        "ja": "無料で使いやすいツールであなたにぴったりのスキーを見つけよう！初心者から経験豊富なスキーヤーまで対応、私たちのサービスはあなたのスキルレベル、スタイル、そして地形の好みに合った理想のスキーモデルを見つけるお手伝いをします。スキーをして、忘れられない冒険を体験しましょう。今すぐ試してみてください - 簡単、正確で、完全に無料です！",
        "es": "¡Descubre tu pareja de esquí perfecta con nuestra herramienta gratuita y fácil de usar! Diseñada tanto para principiantes como para esquiadores experimentados, nuestro servicio te ayuda a encontrar el modelo de esquí ideal que se adapte a tu nivel de habilidad, estilo y preferencias de terreno. Haz que tu próxima aventura en esquí sea inolvidable con esquís que son perfectos para ti. ¡Pruébalo ahora, sin esfuerzo, preciso y totalmente gratis!",
        "de": "Entdecken Sie Ihren perfekten Ski-Partner mit unserem kostenlosen und benutzerfreundlichen Tool! Angepasst sowohl für Anfänger als auch für erfahrene Skifahrer, hilft unser Service Ihnen, das ideale Skimodell zu finden, das zu Ihrem Könnensniveau, Stil und Geländevorlieben passt. Machen Sie Ihr nächstes Skiabenteuer unvergesslich mit Skiern, die genau richtig für Sie sind. Probieren Sie es jetzt aus – mühelos, genau und absolut kostenlos!",
        "pl": "Odkryj swoją idealną parę nart za pomocą naszego darmowego i przyjaznego dla użytkownika narzędzia! Skrojony zarówno dla początkujących, jak i doświadczonych narciarzy, nasza usługa pomaga znaleźć idealny model nart, który pasuje do Twojego poziomu umiejętności, stylu i preferencji terenu. Spraw, aby Twoja kolejna przygoda narciarska była niezapomniana dzięki nartom, które są idealne dla Ciebie. Wypróbuj teraz – bez wysiłku, dokładnie i całkowicie za darmo!",
        "fr": "Découvrez votre partenaire de ski idéal avec notre outil gratuit et facile à utiliser ! Conçu aussi bien pour les débutants que pour les skieurs chevronnés, notre service vous aide à trouver le modèle de ski idéal adapté à votre niveau de compétence, à votre style et à vos préférences de terrain. Rendez votre prochaine aventure à ski inoubliable avec des skis qui vous conviennent parfaitement. Essayez-le maintenant - sans effort, précis et absolument gratuit !"
        },
    upperTitle: {
        "en": "Pick a ski",
        "nl": "Pick a ski",
        "ja": "Pick a ski",
        "es": "Pick a ski",
        "de": "Pick a ski",
        "pl": "Pick a ski",
        "fr": "Pick a ski"
      },
    title: {
        "en": "The tool to easily find the right ski",
        "nl": "De tool om gemakkelijk de juiste ski te vinden",
        "ja": "簡単に適切なスキーを見つけるためのツール",
        "es": "La herramienta para encontrar fácilmente el esquí adecuado",
        "de": "Das Werkzeug, um einfach den richtigen Ski zu finden",
        "pl": "Narzędzie do łatwego znalezienia odpowiednich nart",
        "fr": "L'outil pour trouver facilement le bon ski"
      },

    explainer: {
        "en": "Fill in the characteristics as they fit your ideal ski. You can also add extra properties for skis with a more specialized purpose.",
        "nl": "Vul de eigenschappen in zoals ze bij jou ideale ski passen. Je kan ook extra eigenschappen toevoegen voor skis met een meer specialistisch doeleinde.",
        "ja": "理想的なスキーに合うように特性を記入してください。より専門的な目的のスキーには、追加の特性を加えることもできます。",
        "es": "Rellena las características según se ajusten a tu esquí ideal. También puedes añadir propiedades adicionales para esquís con un propósito más especializado.",
        "de": "Fülle die Eigenschaften so aus, wie sie zu deinem idealen Ski passen. Du kannst auch zusätzliche Eigenschaften für Skier mit einem spezielleren Zweck hinzufügen.",
        "pl": "Wypełnij cechy tak, aby pasowały do Twoich idealnych nart. Możesz również dodać dodatkowe właściwości dla nart o bardziej specjalistycznym zastosowaniu.",
        "fr": "Remplissez les caractéristiques comme elles conviennent à votre ski idéal. Vous pouvez également ajouter des propriétés supplémentaires pour les skis à des fins plus spécialisées."
      },
    addProperties: {
        "en": "Add extra property",
        "nl": "Voeg extra eigenschap toe",
        "ja": "追加の属性を追加",
        "es": "Añadir propiedad adicional",
        "de": "Zusätzliche Eigenschaft hinzufügen",
        "pl": "Dodaj dodatkową właściwość",
        "fr": "Ajouter une propriété supplémentaire"
      },
    piste: {
        "en": "Slope",
        "nl": "Piste",
        "ja": "スキー場",
        "es": "Pista",
        "de": "Piste",
        "pl": "Stok",
        "fr": "Piste"
      },
    powder: {
        "en": "Powder",
        "nl": "Poedersneeuw",
        "ja": "パウダー",
        "es": "Nieve polvo",
        "de": "Pulverschnee",
        "pl": "Proszek",
        "fr": "Poudreuse"
      },
    level: {
        "en": "Experience",
        "nl": "Ervaring",
        "ja": "経験",
        "es": "Experiencia",
        "de": "Erfahrung",
        "pl": "Doświadczenie",
        "fr": "Expérience"
      },
    playfull: {
        "en": "Stable vs Playfull",
        "nl": "Stabiel vs Speels",
        "ja": "安定 vs プレイフル",
        "es": "Estable vs Juguetón",
        "de": "Stabil vs. Verspielt",
        "pl": "Stabilny vs Zabawny",
        "fr": "Stable vs Joueuse"
      },
    touring: {
        "en": "Touring",
        "nl": "Tourski",
        "ja": "ツーリング",
        "es": "Esquí de travesía",
        "de": "Touren",
        "pl": "Wycieczka",
        "fr": "Randonnée"
      },
    park: {
        "en": "Funpark",
        "nl": "Funpark",
        "ja": "ファンパーク",
        "es": "Funpark",
        "de": "Funpark",
        "pl": "Funpark",
        "fr": "Funpark"
      },
    freeride: {
        "en": "Freeride",
        "nl": "Freeride",
        "ja": "フリーライド",
        "es": "Freeride",
        "de": "Freeride",
        "pl": "Freeride",
        "fr": "Freeride"
      },
    pisteExplainer: {
        "en": "Do you want a ski that is suitable for the slopes? The more you are on the slopes, the higher you fill this in.",
        "nl": "Wil je een ski die geschikt is voor de piste? Hoe meer je op de piste bent, des te hoger je deze invult.",
        "ja": "スキー場に適したスキーが欲しいですか？スキー場にいる時間が長いほど、このスキーを高く評価します。",
        "es": "¿Quieres un esquí adecuado para las pistas? Cuanto más estés en las pistas, más alto lo rellenarás.",
        "de": "Möchtest du einen Ski, der für die Piste geeignet ist? Je mehr du auf der Piste bist, desto höher füllst du dies aus.",
        "pl": "Chcesz narty, które nadają się do jazdy na stoku? Im więcej czasu spędzasz na stoku, tym wyżej wypełniasz to pole.",
        "fr": "Vous voulez un ski adapté aux pistes ? Plus vous êtes sur les pistes, plus vous remplissez ce champ."
      },
    powderExplainer: {
        "en": "Do you want a ski that is suitable for powder? The more you are in the powder, the higher you fill this in.",
        "nl": "Wil je een ski die geschikt is voor poedersneeuw? Hoe meer je in de poedersneeuw bent, des te hoger je deze invult.",
        "ja": "パウダーに適したスキーが欲しいですか？パウダーにいる時間が長いほど、このスキーを高く評価します。",
        "es": "¿Quieres un esquí adecuado para la nieve polvo? Cuanto más estés en la nieve polvo, más alto lo rellenarás.",
        "de": "Möchtest du einen Ski, der für Pulverschnee geeignet ist? Je mehr du im Pulverschnee bist, desto höher füllst du dies aus.",
        "pl": "Chcesz narty, które nadają się do jazdy w proszku? Im więcej czasu spędzasz w proszku, tym wyżej wypełniasz to pole.",
        "fr": "Vous voulez un ski adapté à la poudreuse ? Plus vous êtes dans la poudreuse, plus vous remplissez ce champ."
      },
    levelExplainer: {
        "en": "How often have you been on skis? The more experience you have, the higher you fill this in.",
        "nl": "Hoe vaak heb je al op skis gestaan? Hoe meer ervaring je hebt, des te hoger je deze invult.",
        "ja": "スキーに何回乗ったことがありますか？経験が多いほど、このスキーを高く評価します。",
        "es": "¿Cuántas veces has estado en esquís? Cuanta más experiencia tengas, más alto lo rellenarás.",
        "de": "Wie oft warst du schon auf Skiern? Je mehr Erfahrung du hast, desto höher füllst du dies aus.",
        "pl": "Ile razy byłeś na nartach? Im więcej masz doświadczenia, tym wyżej wypełniasz to pole.",
        "fr": "Combien de fois avez-vous été sur des skis ? Plus vous avez d'expérience, plus vous remplissez ce champ."
      },
    playfullExplainer: {
        "en": "Do you want a heavier stable ski that can also handle some speed, or a more easy to steer playful ski?",
        "nl": "Wil je een zwaardere stabiele ski die ook wat snelheid aankan, of juist een gemakkelijk te sturen speelse ski?",
        "ja": "重い安定したスキーが欲しいですか？それとも、より扱いやすいプレイフルなスキーが欲しいですか？",
        "es": "¿Quieres un esquí estable más pesado que también pueda manejar algo de velocidad, o un esquí más fácil de manejar y juguetón?",
        "de": "Möchtest du einen schwereren stabilen Ski, der auch etwas Geschwindigkeit verträgt, oder einen leichter zu steuernden verspielten Ski?",
        "pl": "Chcesz cięższe, stabilne narty, które mogą również poradzić sobie z dużą prędkością, czy też łatwiejsze w prowadzeniu, zabawne narty?",
        "fr": "Vous voulez un ski plus lourd et stable qui peut aussi supporter une certaine vitesse, ou un ski plus facile à manœuvrer et ludique ?"
      },
    touringExplainer: {
        "en": "Do you want a ski that is focussed on ski touring or maybe go skitouring occasionally?",
        "nl": "Wil je een ski die gericht is op tourskiën of misschien af en toe tourskiën?",
        "ja": "スキーツーリングに特化したスキーが欲しいですか？それとも、たまにスキーツーリングに行きますか？",
        "es": "¿Quieres un esquí enfocado al esquí de travesía o quizás ir de travesía de vez en cuando?",
        "de": "Möchtest du einen Ski, der auf Skitouren ausgerichtet ist oder vielleicht gelegentlich Skitouren geht?",
        "pl": "Chcesz narty skupione na skitouringu, czy może wybierasz się na skitouring od czasu do czasu?",
        "fr": "Vous voulez un ski axé sur le ski de randonnée ou peut-être faire du ski de randonnée de temps en temps ?"
    },
    parkExplainer: {
        "en": "Do you see yourself trying a run in the funpark once or twice, or are you going to spend all day every day in the funpark?",
        "nl": "Zie je jezelf een keer of twee een run in het funpark proberen, of ga je de hele dag elke dag in het funpark doorbrengen?",
        "ja": "ファンパークで一度か二度滑ってみたいですか？それとも、毎日ファンパークに一日中滑りに行きますか？",
        "es": "¿Te ves probando una carrera en el funpark una o dos veces, o vas a pasar todo el día todos los días en el funpark?",
        "de": "Kannst du dir vorstellen, einmal oder zweimal einen Lauf im Funpark zu versuchen, oder wirst du jeden Tag den ganzen Tag im Funpark verbringen?",
        "pl": "Czy widzisz siebie spróbować przebiegu w funparku raz lub dwa razy, czy zamierzasz spędzić cały dzień codziennie w funparku?",
        "fr": "Vous vous voyez essayer une course dans le funpark une ou deux fois, ou vous allez passer toute la journée tous les jours dans le funpark ?"
    },
    freerideExplainer: {
        "en": "A freeride orriented ski is a ski that works well outside the marked slopes. In all conditions so not just for powder skiing.",
        "nl": "Een freeride georiënteerde ski is een ski die goed werkt buiten de gemarkeerde pistes. In alle omstandigheden dus niet alleen voor poederskiën.",
        "ja": "フリーライド志向のスキーは、マークされたスキー場の外でもうまく機能するスキーです。すべての条件で、パウダースキーだけではありません。",
        "es": "Un esquí orientado al freeride es un esquí que funciona bien fuera de las pistas marcadas. En todas las condiciones, así que no sólo para esquí en polvo.",
        "de": "Ein freeride-orientierter Ski ist ein Ski, der außerhalb der markierten Pisten gut funktioniert. In allen Bedingungen, also nicht nur für Pulverschnee-Ski.",
        "pl": "Narty zorientowane na freeride to narty, które dobrze sprawdzają się poza oznaczonymi stokami. We wszystkich warunkach, więc nie tylko do jazdy w proszku.",
        "fr": "Un ski orienté freeride est un ski qui fonctionne bien en dehors des pistes balisées. Dans toutes les conditions, donc pas seulement pour le ski en poudreuse."
    },
    weight: {
        "en": "Weight (in kg)",
        "nl": "Gewicht (in kg)",
        "ja": "重量（kg）",
        "es": "Peso (en kg)",
        "de": "Gewicht (in kg)",
        "pl": "Waga (w kg)",
        "fr": "Poids (en kg)"
    },
    height: {
        "en": "Height (in cm)",
        "nl": "Lengte (in cm)",
        "ja": "身長（cm）",
        "es": "Altura (en cm)",
        "de": "Größe (in cm)",
        "pl": "Wzrost (w cm)",
        "fr": "Taille (en cm)"
    },
    fitness: {
        "en": "Fitness (from 1 to 10)",
        "nl": "Fitheid (van 1 tot 10)",
        "ja": "フィットネス（1から10まで）",
        "es": "Forma física (de 1 a 10)",
        "de": "Fitness (von 1 bis 10)",
        "pl": "Forma (od 1 do 10)",
        "fr": "Forme physique (de 1 à 10)"
    },
    getRecommendations: {
        "en": "Load my recommendations",
        "nl": "Laad mijn aanbevelingen",
        "ja": "私のおすすめを読み込む",
        "es": "Cargar mis recomendaciones",
        "de": "Meine Empfehlungen laden",
        "pl": "Załaduj moje rekomendacje",
        "fr": "Charger mes recommandations"
    },
    pisteOptions: {
        "en": {
            1: "1: Never on the slopes",
            2: "2: Sometimes on the slopes",
            3: "3: Regularly on the slopes",
            4: "4: Often on the slopes",
            5: "5: Always on the slopes",
        },
        "nl": {
            1: "1: Nooit op de piste",
            2: "2: Soms op de piste",
            3: "3: Regelmatig op de piste",
            4: "4: Vaak op de piste",
            5: "5: Altijd op de piste",
        },
        "ja": {
            1: "1: スキー場に行ったことがない",
            2: "2: スキー場に時々行く",
            3: "3: スキー場に定期的に行く",
            4: "4: スキー場によく行く",
            5: "5: スキー場にいつも行く",
        },
        "es": {
            1: "1: Nunca en las pistas",
            2: "2: A veces en las pistas",
            3: "3: Regularmente en las pistas",
            4: "4: A menudo en las pistas",
            5: "5: Siempre en las pistas",
        },
        "de": {
            1: "1: Nie auf der Piste",
            2: "2: Manchmal auf der Piste",
            3: "3: Regelmäßig auf der Piste",
            4: "4: Oft auf der Piste",
            5: "5: Immer auf der Piste",
        },
        "pl": {
            1: "1: Nigdy na stoku",
            2: "2: Czasami na stoku",
            3: "3: Regularnie na stoku",
            4: "4: Często na stoku",
            5: "5: Zawsze na stoku",
        },
        "fr": {
            1: "1: Jamais sur les pistes",
            2: "2: Parfois sur les pistes",
            3: "3: Régulièrement sur les pistes",
            4: "4: Souvent sur les pistes",
            5: "5: Toujours sur les pistes",
        },
    },
    powderOptions: {
        "en": {
            1: "1: Never in the powder",
            2: "2: Sometimes in the powder",
            3: "3: Regularly in the powder",
            4: "4: Often in the powder",
            5: "5: Purely for powder",
        },
        "nl": {
            1: "1: Nooit in de poeder",
            2: "2: Soms in de poeder",
            3: "3: Regelmatig in de poeder",
            4: "4: Vaak in de poeder",
            5: "5: Puur voor poeder",
        },
        "ja": {
            1: "1: パウダーに行ったことがない",
            2: "2: パウダーに時々行く",
            3: "3: パウダーに定期的に行く",
            4: "4: パウダーによく行く",
            5: "5: パウダーのためだけに",
        },
        "es": {
            1: "1: Nunca en la nieve polvo",
            2: "2: A veces en la nieve polvo",
            3: "3: Regularmente en la nieve polvo",
            4: "4: A menudo en la nieve polvo",
            5: "5: Puro para la nieve polvo",
        },
        "de": {
            1: "1: Nie im Pulverschnee",
            2: "2: Manchmal im Pulverschnee",
            3: "3: Regelmäßig im Pulverschnee",
            4: "4: Oft im Pulverschnee",
            5: "5: Rein für Pulverschnee",
        },
        "pl": {
            1: "1: Nigdy w proszku",
            2: "2: Czasami w proszku",
            3: "3: Regularnie w proszku",
            4: "4: Często w proszku",
            5: "5: Czysty proszek",
        },
        "fr": {
            1: "1: Jamais dans la poudreuse",
            2: "2: Parfois dans la poudreuse",
            3: "3: Régulièrement dans la poudreuse",
            4: "4: Souvent dans la poudreuse",
            5: "5: Purement pour la poudreuse",
        },
    },
    levelOptions: {
        "en": {
            1: "1: Never skied before",
            2: "2: Skied a few times",
            3: "3: Skied once a year",
            4: "4: Skied a few times a year",
            5: "5: Skiing all winter",
        },
        "nl": {
            1: "1: Nooit geskied",
            2: "2: Een paar keer geskied",
            3: "3: Een keer per jaar skien",
            4: "4: Een paar keer per jaar geskied",
            5: "5: Altijd in de bergen",
        },
        "ja": {
            1: "1: スキーをしたことがない",
            2: "2: 数回スキーをした",
            3: "3: 1年に1回スキーをした",
            4: "4: 1年に数回スキーをした",
            5: "5: 冬はいつもスキーをしている",
        },
        "es": {
            1: "1: Nunca esquiado antes",
            2: "2: Esquiado unas pocas veces",
            3: "3: Esquiado una vez al año",
            4: "4: Esquiado unas pocas veces al año",
            5: "5: Esquí todo el invierno",
        },
        "de": {
            1: "1: Noch nie Ski gefahren",
            2: "2: Ein paar Mal Ski gefahren",
            3: "3: Einmal im Jahr Ski gefahren",
            4: "4: Ein paar Mal im Jahr Ski gefahren",
            5: "5: Immer im Winter Ski fahren",
        },
        "pl": {
            1: "1: Nigdy nie jeździł na nartach",
            2: "2: Jeździł kilka razy",
            3: "3: Jeździł raz w roku",
            4: "4: Jeździł kilka razy w roku",
            5: "5: Jeździ na nartach całą zimę",
        },
        "fr": {
            1: "1: Jamais skié auparavant",
            2: "2: Skier quelques fois",
            3: "3: Skier une fois par an",
            4: "4: Skier quelques fois par an",
            5: "5: Skier tout l'hiver",
        },
    },
    playfullOptions: {
        "en": {
            1: "1: Super stiff",
            2: "2: Reasonably stable",
            3: "3: All-round",
            4: "4: Easy to steer",
            5: "5: Jumps and tricks",
        },
        "nl": {
            1: "1: Super stijf",
            2: "2: Redelijk stabiel",
            3: "3: All-round",
            4: "4: Gemakkelijk te draaien",
            5: "5: Sprinten en stunten",
        },
        "ja": {
            1: "1: スーパースタブル",
            2: "2: 理にかなった安定",
            3: "3: オールラウンド",
            4: "4: 操作しやすい",
            5: "5: ジャンプとトリック",
        },
        "es": {
            1: "1: Super estable",
            2: "2: Razonablemente estable",
            3: "3: Todo terreno",
            4: "4: Fácil de maniobrar",
            5: "5: Saltos y trucos",
        },
        "de": {
            1: "1: Super stabil",
            2: "2: Vernünftig stabil",
            3: "3: Allround",
            4: "4: Leicht zu lenken",
            5: "5: Sprünge und Tricks",
        },
        "pl": {
            1: "1: Super stabilny",
            2: "2: Rozsądnie stabilny",
            3: "3: Wszystkie rundy",
            4: "4: Łatwy do sterowania",
            5: "5: Skoki i sztuczki",
        },
        "fr": {
            1: "1: Super stable",
            2: "2: Raisonnablement stable",
            3: "3: Tout terrain",
            4: "4: Facile à diriger",
            5: "5: Sauts et astuces",
        },
    },
    touringOptions: {
        "en": {
            1: "1: Never skitouring",
            2: "2: Sometimes skitouring",
            3: "3: Regular skitouring",
            4: "4: Mostly skitouring",
            5: "5: Always skitouring",
        },
        "nl": {
            1: "1: Nooit tourskiën",
            2: "2: Soms tourskiën",
            3: "3: Regelmatig tourskiën",
            4: "4: Meestal tourskiën",
            5: "5: Altijd tourskiën",
        },
        "ja": {
            1: "1: スキーツーリングしたことがない",
            2: "2: 時々スキーツーリングする",
            3: "3: 定期的にスキーツーリングする",
            4: "4: ほとんどスキーツーリングする",
            5: "5: いつもスキーツーリングする",
        },
        "es": {
            1: "1: Nunca esquiado antes",
            2: "2: Esquiado unas pocas veces",
            3: "3: Esquiado una vez a la semana",
            4: "4: Esquiado unas pocas veces a la semana",
            5: "5: Esquí todos los días",
        },
        "de": {
            1: "1: Noch nie Skitouren gegangen",
            2: "2: Manchmal Skitouren",
            3: "3: Regelmäßig Skitouren",
            4: "4: Meistens Skitouren",
            5: "5: Immer Skitouren",
        },
        "pl": {
            1: "1: Nigdy nie jeździł na skitouringu",
            2: "2: Czasami skitouring",
            3: "3: Regularnie skitouring",
            4: "4: Przeważnie skitouring",
            5: "5: Zawsze skitouring",
        },
        "fr": {
            1: "1: Jamais ski de randonnée",
            2: "2: Parfois ski de randonnée",
            3: "3: Randonnée régulière",
            4: "4: Randonnée la plupart du temps",
            5: "5: Toujours ski de randonnée",
        },
    },
    parkOptions: {
        "en": {
            1: "1: Never in the funpark",
            2: "2: Sometimes in the funpark",
            3: "3: Regularly in the funpark",
            4: "4: Often in the funpark",
            5: "5: Always in the funpark",
        },
        "nl": {
            1: "1: Nooit in het funpark",
            2: "2: Soms in het funpark",
            3: "3: Regelmatig in het funpark",
            4: "4: Vaak in het funpark",
            5: "5: Altijd in het funpark",
        },
        "ja": {
            1: "1: ファンパークに行ったことがない",
            2: "2: ファンパークに時々行く",
            3: "3: ファンパークに定期的に行く",
            4: "4: ファンパークによく行く",
            5: "5: ファンパークにいつも行く",
        },
        "es": {
            1: "1: Nunca en el funpark",
            2: "2: A veces en el funpark",
            3: "3: Regularmente en el funpark",
            4: "4: A menudo en el funpark",
            5: "5: Siempre en el funpark",
        },
        "de": {
            1: "1: Noch nie im Funpark",
            2: "2: Manchmal im Funpark",
            3: "3: Regelmäßig im Funpark",
            4: "4: Oft im Funpark",
            5: "5: Immer im Funpark",
        },
        "pl": {
            1: "1: Nigdy w funparku",
            2: "2: Czasami w funparku",
            3: "3: Regularnie w funparku",
            4: "4: Często w funparku",
            5: "5: Zawsze w funparku",
        },
        "fr": {
            1: "1: Jamais dans le funpark",
            2: "2: Parfois dans le funpark",
            3: "3: Régulièrement dans le funpark",
            4: "4: Souvent dans le funpark",
            5: "5: Toujours dans le funpark",
        },
    },
    freerideOptions: {
        "en": {
            1: "1: Never freeride",
            2: "2: Sometimes freeride",
            3: "3: Regularly freeride",
            4: "4: Often freeride",
            5: "5: Always freeride",
        },
        "nl": {
            1: "1: Nooit freeriden",
            2: "2: Soms freeriden",
            3: "3: Regelmatig freeriden",
            4: "4: Vaak freeriden",
            5: "5: Altijd freeriden",
        },
        "ja": {
            1: "1: フリーライドしたことがない",
            2: "2: 時々フリーライドする",
            3: "3: 定期的にフリーライドする",
            4: "4: よくフリーライドする",
            5: "5: いつもフリーライドする",
        },
        "es": {
            1: "1: Nunca esquiado antes",
            2: "2: Esquiado unas pocas veces",
            3: "3: Esquiado una vez a la semana",
            4: "4: Esquiado unas pocas veces a la semana",
            5: "5: Esquí todos los días",
        },
        "de": {
            1: "1: Noch nie Freeride",
            2: "2: Manchmal Freeride",
            3: "3: Regelmäßig Freeride",
            4: "4: Oft Freeride",
            5: "5: Immer Freeride",
        },
        "pl": {
            1: "1: Nigdy nie jeździł na freeride",
            2: "2: Czasami freeride",
            3: "3: Regularnie freeride",
            4: "4: Często freeride",
            5: "5: Zawsze freeride",
        },
        "fr": {
            1: "1: Jamais de freeride",
            2: "2: Parfois de freeride",
            3: "3: Régulièrement de freeride",
            4: "4: Souvent de freeride",
            5: "5: Toujours de freeride",
        },
        
        

    },
}

export default textsPickaski

