const textsHome = {
  metaDescription: {
    "en": "Discover the best skis for your winter adventures with our unbiased comparison tool. Free from big brand influence, we offer honest reviews and detailed comparisons to help you find the perfect pair of skis tailored to your style and skill level. Start comparing now and hit the slopes with confidence!",
    "nl": "Ontdek de beste ski's voor uw winteravonturen met onze onbevooroordeelde vergelijkingstool. Vrij van grote merkinvloed bieden wij eerlijke beoordelingen en gedetailleerde vergelijkingen om u te helpen het perfecte paar ski's te vinden, aangepast aan uw stijl en vaardigheidsniveau. Begin nu met vergelijken en ga vol vertrouwen de pistes op!",
    "de": "Entdecken Sie die besten Ski für Ihre Winterabenteuer mit unserem unvoreingenommenen Vergleichstool. Frei von großen Markeneinflüssen bieten wir ehrliche Bewertungen und detaillierte Vergleiche, um Ihnen zu helfen, das perfekte Paar Ski zu finden, das auf Ihren Stil und Ihr Können zugeschnitten ist. Beginnen Sie jetzt mit dem Vergleich und stürzen Sie sich voller Vertrauen in die Pisten!",
    "ja": "私たちの偏りのない比較ツールで冬の冒険に最適なスキーを見つけましょう。大手ブランドの影響を受けずに、正直なレビューと詳細な比較を提供し、あなたのスタイルとスキルレベルに合った完璧なスキーペアを見つけるお手伝いをします。今すぐ比較を始めて、自信を持って斜面を滑りましょう！",
    "fr": "Découvrez les meilleurs skis pour vos aventures hivernales avec notre outil de comparaison impartial. Libres de l'influence des grandes marques, nous offrons des avis honnêtes et des comparaisons détaillées pour vous aider à trouver la paire de skis parfaite, adaptée à votre style et à votre niveau de compétence. Commencez à comparer maintenant et attaquez les pistes en toute confiance !",
    "es": "Descubra los mejores esquís para sus aventuras de invierno con nuestra herramienta de comparación imparcial. Libres de la influencia de grandes marcas, ofrecemos reseñas honestas y comparaciones detalladas para ayudarle a encontrar el par de esquís perfecto, adaptado a su estilo y nivel de habilidad. ¡Comience a comparar ahora y lance a las pistas con confianza!",
    "pl": "Odkryj najlepsze narty na swoje zimowe przygody z naszym bezstronnym narzędziem do porównań. Wolni od wpływu dużych marek oferujemy szczere recenzje i szczegółowe porównania, aby pomóc Ci znaleźć idealną parę nart dostosowaną do Twojego stylu i poziomu umiejętności. Zacznij porównywać teraz i z ufnością wybierz się na stoki!"
  },
  header: {
    "en": "Pick a ski",
    "nl": "Pick a ski",
    "ja": "スキーを選ぶ",
    "es": "Elige unos esquís",
    "de": "Wähle einen Ski",
    "pl": "Wybierz narty",
    "fr": "Choisissez un ski"
  },
  title: {
    "en": "Ski Selector",
    "nl": "Ski Selector",
    "ja": "スキーセレクター",
    "es": "Selector de esquís",
    "de": "Ski-Auswahl",
    "pl": "Selektor nart",
    "fr": "Sélecteur de skis"
  },
  info: {
    "en": "Move the sliders around to find the right ski!",
    "nl": "Gebruik de sliders om de juiste ski's te vinden!",
    "ja": "スライダーを動かして適切なスキーを見つけよう！",
    "es": "¡Mueve los controles deslizantes para encontrar los esquís adecuados!",
    "de": "Bewegen Sie die Schieberegler, um den richtigen Ski zu finden!",
    "pl": "Przesuwaj suwaki, aby znaleźć odpowiednie narty!",
    "fr": "Déplacez les curseurs pour trouver le ski idéal !"
  },
  button: {
    "en": "Find skis!",
    "nl": "Ski's zoeken!",
    "ja": "スキーを探す！",
    "es": "¡Buscar esquís!",
    "de": "Skier finden!",
    "pl": "Znajdź narty!",
    "fr": "Trouver des skis !"
  },
  buttonLoading: {
    "en": "Loading...",
    "nl": "Laden...",
    "ja": "読み込み中...",
    "es": "Cargando...",
    "de": "Lädt...",
    "pl": "Ładowanie...",
    "fr": "Chargement..."
  },
  choicesTitle: {
    "en": "Your top ski choices.",
    "nl": "Onze ski suggesties.",
    "ja": "おすすめのスキー選択肢。",
    "es": "Tus mejores opciones de esquís.",
    "de": "Ihre besten Ski-Auswahlmöglichkeiten.",
    "pl": "Twoje najlepsze wybory nart.",
    "fr": "Vos meilleurs choix de skis."
  },
  welcomeMessage: {
    "en": "Hi there!🙋‍♂️ This tool is brand new, I hope you enjoy it, and would love to hear your opinion!", 
    "nl": "Hey daar!🙋‍♂️ De tool is net nieuw, hopelijk ervaar je het als nuttig, ik ben erg benieuwd naar je mening!",
    "ja": "こんにちは！🙋‍♂️ このツールは真新しいです。楽しんでいただければ幸いです。皆さんの意見をお聞かせください！",
    "es": "¡Hola!🙋‍♂️ Esta herramienta es completamente nueva, espero que la disfrutes y me encantaría escuchar tu opinión.",
    "de": "Hallo!🙋‍♂️ Dieses Tool ist brandneu, ich hoffe, es gefällt Ihnen, und würde gerne Ihre Meinung hören!",
    "pl": "Cześć!🙋‍♂️ To narzędzie jest zupełnie nowe, mam nadzieję, że Ci się spodoba i chętnie usłyszę Twoją opinię!",
    "fr": "Bonjour !🙋‍♂️ Cet outil est tout nouveau, j'espère que vous l'apprécierez et j'aimerais beaucoup entendre votre avis !"
  },
  upperAlert1: {
    "en": "Own a pair of skis? Share your experience on our new Opinions page! 👊🏼",
    "nl": "Bezit u een paar ski's? Deel uw ervaring op onze nieuwe Meningenpagina! 👊🏼",
    "de": "Besitzen Sie ein Paar Ski? Teilen Sie Ihre Erfahrungen auf unserer neuen Meinungsseite! 👊🏼",
    "ja": "スキーをお持ちですか？新しいご意見ページで経験を共有しましょう！👊🏼",
    "fr": "Vous possédez des skis ? Partagez votre expérience sur notre nouvelle page d'Avis ! 👊🏼",
    "es": "¿Tienes unos esquíes? ¡Comparte tu experiencia en nuestra nueva página de Opiniones! 👊🏼",
    "pl": "Masz narty? Podziel się swoimi doświadczeniami na naszej nowej stronie Opinii! 👊🏼"
  },
  upperAlert2: {
    "en": "Opinions page",
    "nl": "Meningen pagina",
    "ja": "意見ページ",
    "es": "Página de opiniones",
    "de": "Meinungsseite",
    "pl": "Strona opinii",
    "fr": "Page des avis"
  },
  selectStandard: {
    "en": "Standard",
    "nl": "Standaard",
    "ja": "スタンダード",
    "es": "Estándar",
    "de": "Standard",
    "pl": "Standardowy",
    "fr": "Standard"
  },
  selectBeginner: {
    "en": "Beginner",
    "nl": "Beginner",
    "ja": "初心者",
    "es": "Principiante",
    "de": "Anfänger",
    "pl": "Początkujący",
    "fr": "Débutant"
  },
  selectRace: {
    "en": "Race",
    "nl": "Race",
    "ja": "レース",
    "es": "Race",
    "de": "Race",
    "pl": "Race",
    "fr": "Race"
  },
  placeholderRace: {
    "en": "At this moment the tool for race skis is not developed yet, priorities are on different aspects of the site right now. However if you would like to assist in its development please send an email to remco@pick-a-ski.com.",
    "nl": "Op dit moment is de tool voor race skis nog niet gemaakt, de prioriteit ligt voor nu op andere onderdelen van de site. Mocht je willen helpen met het maken van de tool voor race skis kan je altijd een email sturen naar remco@pick-a-ski.com.",
    "ja": "現在レース用スキーのツールはまだ開発されていません。現在はサイトの他の側面に優先順位があります。しかし、その開発を手伝いたい場合は、remco@pick-a-ski.comにメールを送ってください。",
    "es": "En este momento, la herramienta para esquís de carrera aún no está desarrollada, las prioridades están en diferentes aspectos del sitio ahora. Sin embargo, si te gustaría ayudar en su desarrollo, por favor envía un correo electrónico a remco@pick-a-ski.com.",
    "de": "Derzeit ist das Werkzeug für Rennskier noch nicht entwickelt, die Prioritäten liegen gerade auf anderen Aspekten der Seite. Wenn Sie jedoch bei der Entwicklung helfen möchten, senden Sie bitte eine E-Mail an remco@pick-a-ski.com.",
    "pl": "W tej chwili narzędzie do nart wyścigowych nie jest jeszcze rozwinięte, priorytety dotyczą obecnie innych aspektów witryny. Jeśli jednak chciałbyś pomóc w jego rozwoju, wyślij e-mail na adres remco@pick-a-ski.com.",
    "fr": "Pour le moment, l'outil pour les skis de course n'est pas encore développé, les priorités sont actuellement sur différents aspects du site. Cependant, si vous souhaitez aider à son développement, veuillez envoyer un email à remco@pick-a-ski.com."
  },
  beginnerSliders: {
    "fitness": {
      "en": {
        1: "My fitness could use some work.",
        2: "My fitness could use some work.",
        3: "I work out weekly.",
        4: "I work out weekly",
        5: "I work out multiple times a week.",
        6: "I work out multiple times a week.",
        7: "I'm fit and work out a lot.",
        8: "I'm fit and work out a lot.",
        9: "I'm in great shape!",
        10: "I'm in great shape!",
      },
      "nl": {
        1: "Mijn conditie is niet zo goed.",
        2: "Mijn conditie is niet zo goed.",
        3: "Ik sport wekelijks.",
        4: "Ik sport wekelijks.",
        5: "Ik sport meerdere keren per week.",
        6: "Ik sport meerdere keren per week.",
        7: "Ik ben fit en sport veel.",
        8: "Ik ben fit en sport veel.",
        9: "Ik voel me een jonge god",
        10: "Ik voel me een jonge god",
      },
      "ja": {
        1: "もっとフィットネスを改善したい。",
        2: "もっとフィットネスを改善したい。",
        3: "週に1回は運動しています。",
        4: "週に1回は運動しています。",
        5: "週に複数回運動しています。",
        6: "週に複数回運動しています。",
        7: "フィットでたくさん運動しています。",
        8: "フィットでたくさん運動しています。",
        9: "とても良い体調です！",
        10: "とても良い体調です！",
      },
      "es": {
        1: "Podría mejorar mi condición física.",
        2: "Podría mejorar mi condición física.",
        3: "Hago ejercicio semanalmente.",
        4: "Hago ejercicio semanalmente.",
        5: "Hago ejercicio varias veces a la semana.",
        6: "Hago ejercicio varias veces a la semana.",
        7: "Estoy en forma y hago mucho ejercicio.",
        8: "Estoy en forma y hago mucho ejercicio.",
        9: "¡Estoy en excelente forma!",
        10: "¡Estoy en excelente forma!",
      },
      "de": {
        1: "Meine Fitness könnte etwas Arbeit gebrauchen.",
        2: "Meine Fitness könnte etwas Arbeit gebrauchen.",
        3: "Ich trainiere wöchentlich.",
        4: "Ich trainiere wöchentlich.",
        5: "Ich trainiere mehrmals pro Woche.",
        6: "Ich trainiere mehrmals pro Woche.",
        7: "Ich bin fit und trainiere viel.",
        8: "Ich bin fit und trainiere viel.",
        9: "Ich bin in großartiger Form!",
        10: "Ich bin in großartiger Form!",
      },
      "pl": {
        1: "Mogłabym popracować nad kondycją.",
        2: "Mogłabym popracować nad kondycją.",
        3: "Ćwiczę co tydzień.",
        4: "Ćwiczę co tydzień.",
        5: "Ćwiczę kilka razy w tygodniu.",
        6: "Ćwiczę kilka razy w tygodniu.",
        7: "Jestem w dobrej formie i dużo ćwiczę.",
        8: "Jestem w dobrej formie i dużo ćwiczę.",
        9: "Jestem w świetnej kondycji!",
        10: "Jestem w świetnej kondycji!",
      },
      "fr": {
        1: "Ma condition physique pourrait être améliorée.",
        2: "Ma condition physique pourrait être améliorée.",
        3: "Je fais de l'exercice chaque semaine.",
        4: "Je fais de l'exercice chaque semaine.",
        5: "Je fais de l'exercice plusieurs fois par semaine.",
        6: "Je fais de l'exercice plusieurs fois par semaine.",
        7: "Je suis en forme et je fais beaucoup d'exercice.",
        8: "Je suis en forme et je fais beaucoup d'exercice.",
        9: "Je suis en excellente forme !",
        10: "Je suis en excellente forme !",
      },
    },
    "playfull": {
      "en": {
        1: "I want to focus on carving.",
        2: "I want to focus on carving.",
        3: "I just want to ski casually.",
        4: "I just want to ski casually.",
        5: "I want an all-round ski.",
        6: "I want an all-round ski.",
        7: "I would like to play around.",
        8: "I would like to play around.",
        9: "I would like to learn some tricks!",
        10: "I would like to learn some tricks!",
      },
      "nl": {
        1: "Ik wil de perfecte bocht skiën.",
        2: "Ik wil de perfecte bocht skiën.",
        3: "Ik wil comfortabel skiën.",
        4: "Ik wil comfortabel skiën.",
        5: "Ik wil een all-round ski.",
        6: "Ik wil een all-round ski.",
        7: "Ik wil een speelse ski.",
        8: "Ik wil een speelse ski.",
        9: "Ik wil wel wat trucjes leren!",
        10: "Ik wil wel wat trucjes leren!",
      },
      "ja": {
        1: "カービングに集中したい。",
        2: "カービングに集中したい。",
        3: "カジュアルにスキーを楽しみたい。",
        4: "カジュアルにスキーを楽しみたい。",
        5: "オールラウンドなスキーが欲しい。",
        6: "オールラウンドなスキーが欲しい。",
        7: "遊び心のあるスキーがいい。",
        8: "遊び心のあるスキーがいい。",
        9: "トリックをいくつか学びたい！",
        10: "トリックをいくつか学びたい！",
      },
      "es": {
        1: "Quiero centrarme en el carving.",
        2: "Quiero centrarme en el carving.",
        3: "Solo quiero esquiar de manera casual.",
        4: "Solo quiero esquiar de manera casual.",
        5: "Quiero unos esquís todoterreno.",
        6: "Quiero unos esquís todoterreno.",
        7: "Me gustaría jugar un poco.",
        8: "Me gustaría jugar un poco.",
        9: "¡Me gustaría aprender algunos trucos!",
        10: "¡Me gustaría aprender algunos trucos!",
      },
      "de": {
        1: "Ich möchte mich auf das Carving konzentrieren.",
        2: "Ich möchte mich auf das Carving konzentrieren.",
        3: "Ich möchte nur gelegentlich Ski fahren.",
        4: "Ich möchte nur gelegentlich Ski fahren.",
        5: "Ich möchte einen Allround-Ski.",
        6: "Ich möchte einen Allround-Ski.",
        7: "Ich möchte etwas herumspielen.",
        8: "Ich möchte etwas herumspielen.",
        9: "Ich würde gerne einige Tricks lernen!",
        10: "Ich würde gerne einige Tricks lernen!",
      },
      "pl": {
        1: "Chcę skupić się na carvingu.",
        2: "Chcę skupić się na carvingu.",
        3: "Chcę po prostu jeździć na nartach rekreacyjnie.",
        4: "Chcę po prostu jeździć na nartach rekreacyjnie.",
        5: "Chcę wszechstronne narty.",
        6: "Chcę wszechstronne narty.",
        7: "Chciałbym trochę poszaleć.",
        8: "Chciałbym trochę poszaleć.",
        9: "Chciałbym nauczyć się kilku sztuczek!",
        10: "Chciałbym nauczyć się kilku sztuczek!",
      },
      "fr": {
        1: "Je veux me concentrer sur le carving.",
        2: "Je veux me concentrer sur le carving.",
        3: "Je veux juste skier occasionnellement.",
        4: "Je veux juste skier occasionnellement.",
        5: "Je veux un ski polyvalent.",
        6: "Je veux un ski polyvalent.",
        7: "J'aimerais m'amuser un peu.",
        8: "J'aimerais m'amuser un peu.",
        9: "J'aimerais apprendre quelques astuces !",
        10: "J'aimerais apprendre quelques astuces !",
      },
    },
  },
  sliders: {
    "level": {
      "en": {
        1: "I never skied before.",
        2: "I never skied before.",
        3: "I've skied a couple of weeks.",
        4: "I've skied a couple of weeks.",
        5: "I ski 1-10 days a year.",
        6: "I ski 1-10 days a year.",
        7: "I ski multiple weeks every year.",
        8: "I ski multiple weeks every year.",
        9: "I live in the mountains!",
        10: "I live in the mountains!",
      },
      "nl": {
        1: "Ik heb nog nooit geskied.",
        2: "Ik heb nog nooit geskied.",
        3: "Ik heb een paar weken ervaring.",
        4: "Ik heb een paar weken ervaring.",
        5: "Ik ski 1-10 dagen per jaar.",
        6: "Ik ski 1-10 dagen per jaar.",
        7: "Ik ski een paar weken per jaar.",
        8: "Ik ski een paar weken per jaar.",
        9: "Ik leef in de bergen!",
        10: "Ik leef in de bergen!",
      },
      "ja": {
        1: "スキーは初めてです。",
        2: "スキーは初めてです。",
        3: "数週間スキーの経験があります。",
        4: "数週間スキーの経験があります。",
        5: "年に1-10日間スキーをします。",
        6: "年に1-10日間スキーをします。",
        7: "毎年数週間スキーをします。",
        8: "毎年数週間スキーをします。",
        9: "山で暮らしています！",
        10: "山で暮らしています！",
      },
      "es": {
        1: "Nunca he esquiado antes.",
        2: "Nunca he esquiado antes.",
        3: "He esquiado un par de semanas.",
        4: "He esquiado un par de semanas.",
        5: "Esquío 1-10 días al año.",
        6: "Esquío 1-10 días al año.",
        7: "Esquío varias semanas cada año.",
        8: "Esquío varias semanas cada año.",
        9: "¡Vivo en las montañas!",
        10: "¡Vivo en las montañas!",
      },
      "de": {
        1: "Ich habe noch nie Ski gefahren.",
        2: "Ich habe noch nie Ski gefahren.",
        3: "Ich habe ein paar Wochen Erfahrung.",
        4: "Ich habe ein paar Wochen Erfahrung.",
        5: "Ich fahre 1-10 Tage im Jahr Ski.",
        6: "Ich fahre 1-10 Tage im Jahr Ski.",
        7: "Ich fahre jedes Jahr mehrere Wochen Ski.",
        8: "Ich fahre jedes Jahr mehrere Wochen Ski.",
        9: "Ich lebe in den Bergen!",
        10: "Ich lebe in den Bergen!",
      },
      "pl": {
        1: "Nigdy wcześniej nie jeździłem na nartach.",
        2: "Nigdy wcześniej nie jeździłem na nartach.",
        3: "Mam kilkutygodniowe doświadczenie.",
        4: "Mam kilkutygodniowe doświadczenie.",
        5: "Jeżdżę na nartach 1-10 dni w roku.",
        6: "Jeżdżę na nartach 1-10 dni w roku.",
        7: "Jeżdżę na nartach kilka tygodni każdego roku.",
        8: "Jeżdżę na nartach kilka tygodni każdego roku.",
        9: "Mieszkam w górach!",
        10: "Mieszkam w górach!",
      },
      "fr": {
        1: "Je n'ai jamais skié auparavant.",
        2: "Je n'ai jamais skié auparavant.",
        3: "J'ai skié quelques semaines.",
        4: "J'ai skié quelques semaines.",
        5: "Je skie 1-10 jours par an.",
        6: "Je skie 1-10 jours par an.",
        7: "Je skie plusieurs semaines chaque année.",
        8: "Je skie plusieurs semaines chaque année.",
        9: "Je vis dans les montagnes !",
        10: "Je vis dans les montagnes !",
      },
    },
    "piste": {
      "en": {
        1: "I never ski on piste.",
        2: "I never ski on piste.",
        3: "I won't use this ski on piste.",
        4: "I won't use this ski on piste.",
        5: "I want it to be decent on piste.",
        6: "I want it to be decent on piste.",
        7: "I spend most days on piste.",
        8: "I spend most days on piste.",
        9: "Skiing slopes is my life!",
        10: "Skiing slopes is my life!",
      },
      "nl": {
        1: "Piste is niet belangrijk.",
        2: "Piste is niet belangrijk.",
        3: "Ik kom zelden op de piste.",
        4: "Ik kom zelden op de piste.",
        5: "Af en toe een rondje op de piste.",
        6: "Af en toe een rondje op de piste.",
        7: "Ik ben meestal op de piste.",
        8: "Ik ben meestal op de piste.",
        9: "Een ski speciaal voor de piste!",
        10: "Een ski speciaal voor de piste!",
      },
      "ja": {
        1: "ピステでスキーをすることはありません。",
        2: "ピステでスキーをすることはありません。",
        3: "このスキーをピステで使うことはありません。",
        4: "このスキーをピステで使うことはありません。",
        5: "ピステでまずまずの性能を望みます。",
        6: "ピステでまずまずの性能を望みます。",
        7: "ほとんどの日をピステで過ごします。",
        8: "ほとんどの日をピステで過ごします。",
        9: "スキースロープは私の人生です！",
        10: "スキースロープは私の人生です！",
      },
      "es": {
        1: "Nunca esquío en pista.",
        2: "Nunca esquío en pista.",
        3: "No usaré estos esquís en pista.",
        4: "No usaré estos esquís en pista.",
        5: "Quiero que sean decentes en pista.",
        6: "Quiero que sean decentes en pista.",
        7: "Paso la mayoría de los días en pista.",
        8: "Paso la mayoría de los días en pista.",
        9: "¡Esquiar en pistas es mi vida!",
        10: "¡Esquiar en pistas es mi vida!",
      },
      "de": {
        1: "Ich fahre nie auf der Piste.",
        2: "Ich fahre nie auf der Piste.",
        3: "Ich werde diese Skier nicht auf der Piste verwenden.",
        4: "Ich werde diese Skier nicht auf der Piste verwenden.",
        5: "Ich möchte, dass sie auf der Piste ordentlich sind.",
        6: "Ich möchte, dass sie auf der Piste ordentlich sind.",
        7: "Ich verbringe die meisten Tage auf der Piste.",
        8: "Ich verbringe die meisten Tage auf der Piste.",
        9: "Skifahren auf den Pisten ist mein Leben!",
        10: "Skifahren auf den Pisten ist mein Leben!",
      },
      "pl": {
        1: "Nigdy nie jeżdżę na nartach na trasie.",
        2: "Nigdy nie jeżdżę na nartach na trasie.",
        3: "Nie będę używać tych nart na trasie.",
        4: "Nie będę używać tych nart na trasie.",
        5: "Chcę, aby były przyzwoite na trasie.",
        6: "Chcę, aby były przyzwoite na trasie.",
        7: "Większość dni spędzam na trasie.",
        8: "Większość dni spędzam na trasie.",
        9: "Narciarstwo na trasach to moje życie!",
        10: "Narciarstwo na trasach to moje życie!",
      },
      "fr": {
        1: "Je ne skie jamais sur piste.",
        2: "Je ne skie jamais sur piste.",
        3: "Je n'utiliserai pas ces skis sur piste.",
        4: "Je n'utiliserai pas ces skis sur piste.",
        5: "Je veux qu'ils soient corrects sur piste.",
        6: "Je veux qu'ils soient corrects sur piste.",
        7: "Je passe la plupart de mes jours sur piste.",
        8: "Je passe la plupart de mes jours sur piste.",
        9: "Skier sur les pistes, c'est ma vie !",
        10: "Skier sur les pistes, c'est ma vie !",
      },
    },
    "powder": {
      "en": {
        1: "I never ski powder.",
        2: "I never ski powder.",
        3: "I like fresh snow on the slopes.",
        4: "I like fresh snow on the slopes.",
        5: "I like to ski between slopes",
        6: "I like to ski between slopes",
        7: "I like long powder runs",
        8: "I like long powder runs",
        9: "I travel for deep powder!",
        10: "I travel for deep powder!",
      },
      "nl": {
        1: "Ik ski nooit in de poeder.",
        2: "Ik ski nooit in de poeder.",
        3: "Poeder op de piste is leuk.",
        4: "Poeder op de piste is leuk.",
        5: "Ik ski wel eens tussen de pistes",
        6: "Ik ski wel eens tussen de pistes",
        7: "Ik doe graag lange poeder runs",
        8: "Ik doe graag lange poeder runs",
        9: "Ik wil alleen maar poederskiën!",
        10: "Ik wil alleen maar poederskiën!",
      },
      "ja": {
        1: "パウダースノーでスキーはしません。",
        2: "パウダースノーでスキーはしません。",
        3: "斜面の新雪が好きです。",
        4: "斜面の新雪が好きです。",
        5: "斜面の間でスキーをします",
        6: "斜面の間でスキーをします",
        7: "長いパウダーランが好きです",
        8: "長いパウダーランが好きです",
        9: "深いパウダーを求めて旅行します！",
        10: "深いパウダーを求めて旅行します！",
      },
      "es": {
        1: "Nunca esquío en polvo.",
        2: "Nunca esquío en polvo.",
        3: "Me gusta la nieve fresca en las pistas.",
        4: "Me gusta la nieve fresca en las pistas.",
        5: "Me gusta esquiar entre pistas",
        6: "Me gusta esquiar entre pistas",
        7: "Me gustan las largas bajadas en polvo",
        8: "Me gustan las largas bajadas en polvo",
        9: "¡Viajo en busca de polvo profundo!",
        10: "¡Viajo en busca de polvo profundo!",
      },
      "de": {
        1: "Ich fahre nie auf Pulverschnee.",
        2: "Ich fahre nie auf Pulverschnee.",
        3: "Ich mag frischen Schnee auf den Pisten.",
        4: "Ich mag frischen Schnee auf den Pisten.",
        5: "Ich fahre gerne zwischen den Pisten",
        6: "Ich fahre gerne zwischen den Pisten",
        7: "Ich mag lange Abfahrten im Pulverschnee",
        8: "Ich mag lange Abfahrten im Pulverschnee",
        9: "Ich reise für tiefen Pulverschnee!",
        10: "Ich reise für tiefen Pulverschnee!",
      },
      "pl": {
        1: "Nigdy nie jeżdżę na nartach w proszku.",
        2: "Nigdy nie jeżdżę na nartach w proszku.",
        3: "Lubię świeży śnieg na stokach.",
        4: "Lubię świeży śnieg na stokach.",
        5: "Lubię jeździć na nartach między stokami",
        6: "Lubię jeździć na nartach między stokami",
        7: "Lubię długie zjazdy na proszku",
        8: "Lubię długie zjazdy na proszku",
        9: "Podróżuję w poszukiwaniu głębokiego proszku!",
        10: "Podróżuję w poszukiwaniu głębokiego proszku!",
      },
      "fr": {
        1: "Je ne skie jamais dans la poudreuse.",
        2: "Je ne skie jamais dans la poudreuse.",
        3: "J'aime la neige fraîche sur les pistes.",
        4: "J'aime la neige fraîche sur les pistes.",
        5: "J'aime skier entre les pistes",
        6: "J'aime skier entre les pistes",
        7: "J'aime les longues courses dans la poudreuse",
        8: "J'aime les longues courses dans la poudreuse",
        9: "Je voyage pour la poudreuse profonde !",
        10: "Je voyage pour la poudreuse profonde !",
      },
    },
    "freeride": {
      "en": {
        1: "I don't care about freeride.",
        2: "I don't care about freeride.",
        3: "I like to ski trails in the forest",
        4: "I like to ski trails in the forest",
        5: "I occasionally go off-piste",
        6: "I occasionally go off-piste",
        7: "I'm often looking for cool lines",
        8: "I'm often looking for cool lines",
        9: "I ride freeride competitions!",
        10: "I ride freeride competitions!",
      },
      "nl": {
        1: "Freeriden is niets voor mij.",
        2: "Freeriden is niets voor mij.",
        3: "Ik pak af en toe wel een bospaadje.",
        4: "Ik pak af en toe wel een bospaadje.",
        5: "Ik ski wel eens buiten de piste.",
        6: "Ik ski wel eens buiten de piste.",
        7: "Vaak ben ik buiten de piste.",
        8: "Vaak ben ik buiten de piste.",
        9: "Ik ski freeride wedstrijden!",
        10: "Ik ski freeride wedstrijden!",
      },
      "ja": {
        1: "フリーライドには興味がありません。",
        2: "フリーライドには興味がありません。",
        3: "森の中のトレイルをスキーするのが好きです",
        4: "森の中のトレイルをスキーするのが好きです",
        5: "たまにオフピステを滑ります",
        6: "たまにオフピステを滑ります",
        7: "カッコいいラインを探してよく滑ります",
        8: "カッコいいラインを探してよく滑ります",
        9: "フリーライドの競技に出場します！",
        10: "フリーライドの競技に出場します！",
      },
      "es": {
        1: "No me importa el freeride.",
        2: "No me importa el freeride.",
        3: "Me gusta esquiar en senderos en el bosque",
        4: "Me gusta esquiar en senderos en el bosque",
        5: "Ocasionalmente esquío fuera de pista",
        6: "Ocasionalmente esquío fuera de pista",
        7: "A menudo busco buenas líneas",
        8: "A menudo busco buenas líneas",
        9: "¡Participo en competiciones de freeride!",
        10: "¡Participo en competiciones de freeride!",
      },
      "de": {
        1: "Freeriden interessiert mich nicht.",
        2: "Freeriden interessiert mich nicht.",
        3: "Ich fahre gerne auf Waldwegen Ski",
        4: "Ich fahre gerne auf Waldwegen Ski",
        5: "Gelegentlich fahre ich abseits der Pisten",
        6: "Gelegentlich fahre ich abseits der Pisten",
        7: "Ich suche oft nach coolen Linien",
        8: "Ich suche oft nach coolen Linien",
        9: "Ich fahre Freeride-Wettbewerbe!",
        10: "Ich fahre Freeride-Wettbewerbe!",
      },
      "pl": {
        1: "Freeride mnie nie interesuje.",
        2: "Freeride mnie nie interesuje.",
        3: "Lubię jeździć na nartach po ścieżkach w lesie",
        4: "Lubię jeździć na nartach po ścieżkach w lesie",
        5: "Okazjonalnie jeżdżę poza trasami",
        6: "Okazjonalnie jeżdżę poza trasami",
        7: "Często szukam fajnych linii",
        8: "Często szukam fajnych linii",
        9: "Startuję w zawodach freeride!",
        10: "Startuję w zawodach freeride!",
      },
      "fr": {
        1: "Le freeride ne m'intéresse pas.",
        2: "Le freeride ne m'intéresse pas.",
        3: "J'aime skier sur les sentiers en forêt",
        4: "J'aime skier sur les sentiers en forêt",
        5: "Je skie occasionnellement hors-piste",
        6: "Je skie occasionnellement hors-piste",
        7: "Je cherche souvent de bonnes lignes",
        8: "Je cherche souvent de bonnes lignes",
        9: "Je participe à des compétitions de freeride !",
        10: "Je participe à des compétitions de freeride !",
      },
    },
    "touring": {
      "en": {
        1: "I never go skitouring.",
        2: "I never go skitouring.",
        3: "I might try skitouring once.",
        4: "I might try skitouring once.",
        5: "I go touring once or twice",
        6: "I go touring once or twice",
        7: "I like skitouring regularly",
        8: "I like skitouring regularly",
        9: "Skitouring is all I do!",
        10: "Skitouring is all I do!",
      },
      "nl": {
        1: "Ik ga nooit skitouren.",
        2: "Ik ga nooit skitouren.",
        3: "Wellicht ga ik een keertje touren.",
        4: "Wellicht ga ik een keertje touren.",
        5: "Ik tour 1-2 keer per jaar.",
        6: "Ik tour 1-2 keer per jaar.",
        7: "Ik tour met enige regelmaat.",
        8: "Ik tour met enige regelmaat.",
        9: "Skitouren is het enige wat ik doe!",
        10: "Skitouren is het enige wat ik doe!",
      },
      "ja": {
        1: "スキーツーリングはしません。",
        2: "スキーツーリングはしません。",
        3: "スキーツーリングを試してみるかもしれません。",
        4: "スキーツーリングを試してみるかもしれません。",
        5: "年に1、2回スキーツーリングに行きます",
        6: "年に1、2回スキーツーリングに行きます",
        7: "定期的にスキーツーリングを楽しんでいます",
        8: "定期的にスキーツーリングを楽しんでいます",
        9: "スキーツーリングが私のすべてです！",
        10: "スキーツーリングが私のすべてです！",
      },
      "es": {
        1: "Nunca hago esquí de travesía.",
        2: "Nunca hago esquí de travesía.",
        3: "Podría intentar el esquí de travesía alguna vez.",
        4: "Podría intentar el esquí de travesía alguna vez.",
        5: "Voy de travesía una o dos veces",
        6: "Voy de travesía una o dos veces",
        7: "Me gusta hacer esquí de travesía regularmente",
        8: "Me gusta hacer esquí de travesía regularmente",
        9: "¡El esquí de travesía es todo lo que hago!",
        10: "¡El esquí de travesía es todo lo que hago!",
      },
      "de": {
        1: "Ich mache nie Skitouren.",
        2: "Ich mache nie Skitouren.",
        3: "Vielleicht probiere ich einmal Skitouren.",
        4: "Vielleicht probiere ich einmal Skitouren.",
        5: "Ich gehe ein- oder zweimal pro Jahr auf Skitour",
        6: "Ich gehe ein- oder zweimal pro Jahr auf Skitour",
        7: "Ich mag regelmäßiges Skitourengehen",
        8: "Ich mag regelmäßiges Skitourengehen",
        9: "Skitourengehen ist alles, was ich mache!",
        10: "Skitourengehen ist alles, was ich mache!",
      },
      "pl": {
        1: "Nigdy nie uprawiałem skiturowego.",
        2: "Nigdy nie uprawiałem skiturowego.",
        3: "Może kiedyś spróbuję narciarstwa skiturowego.",
        4: "Może kiedyś spróbuję narciarstwa skiturowego.",
        5: "Wybieram się na skitury raz lub dwa razy",
        6: "Wybieram się na skitury raz lub dwa razy",
        7: "Regularnie uprawiam narciarstwo skiturowe",
        8: "Regularnie uprawiam narciarstwo skiturowe",
        9: "Narciarstwo skiturowe to wszystko, co robię!",
        10: "Narciarstwo skiturowe to wszystko, co robię!",
      },
      "fr": {
        1: "Je ne fais jamais de ski de randonnée.",
        2: "Je ne fais jamais de ski de randonnée.",
        3: "Je pourrais essayer le ski de randonnée une fois.",
        4: "Je pourrais essayer le ski de randonnée une fois.",
        5: "Je fais du ski de randonnée une ou deux fois",
        6: "Je fais du ski de randonnée une ou deux fois",
        7: "J'aime faire régulièrement du ski de randonnée",
        8: "J'aime faire régulièrement du ski de randonnée",
        9: "Le ski de randonnée est tout ce que je fais !",
        10: "Le ski de randonnée est tout ce que je fais !",
      },
    },
    "park": {
      "en": {
        1: "I never ski in the funpark.",
        2: "I never ski in the funpark.",
        3: "I might try a funpark lap.",
        4: "I might try a funpark lap.",
        5: "I occasionally ride park.",
        6: "I occasionally ride park.",
        7: "I regularly ride park",
        8: "I regularly ride park",
        9: "I spend most time in the park!",
        10: "I spend most time in the park!",
      },
      "nl": {
        1: "Ik ski nooit in het funpark.",
        2: "Ik ski nooit in het funpark.",
        3: "Ik ga wel ooit park proberen.",
        4: "Ik ga wel ooit park proberen.",
        5: "Ik ski soms in het funpark.",
        6: "Ik ski soms in het funpark.",
        7: "Ik ski regelmatig funpark",
        8: "Ik ski regelmatig funpark",
        9: "Ik ben bijna altijd in het park!",
        10: "Ik ben bijna altijd in het park!",
      },
      "ja": {
        1: "ファンパークでスキーはしません。",
        2: "ファンパークでスキーはしません。",
        3: "ファンパークのラップを試してみるかもしれません。",
        4: "ファンパークのラップを試してみるかもしれません。",
        5: "たまにパークで滑ります。",
        6: "たまにパークで滑ります。",
        7: "定期的にパークで滑ります",
        8: "定期的にパークで滑ります",
        9: "ほとんどの時間をパークで過ごします！",
        10: "ほとんどの時間をパークで過ごします！",
      },
      "es": {
        1: "Nunca esquío en el parque de diversiones.",
        2: "Nunca esquío en el parque de diversiones.",
        3: "Podría probar una vuelta en el parque de diversiones.",
        4: "Podría probar una vuelta en el parque de diversiones.",
        5: "Ocasionalmente esquío en el parque.",
        6: "Ocasionalmente esquío en el parque.",
        7: "Regularmente esquío en el parque",
        8: "Regularmente esquío en el parque",
        9: "¡Paso la mayor parte del tiempo en el parque!",
        10: "¡Paso la mayor parte del tiempo en el parque!",
      },
      "de": {
        1: "Ich fahre nie im Funpark Ski.",
        2: "Ich fahre nie im Funpark Ski.",
        3: "Vielleicht versuche ich mal eine Runde im Funpark.",
        4: "Vielleicht versuche ich mal eine Runde im Funpark.",
        5: "Gelegentlich fahre ich im Park Ski.",
        6: "Gelegentlich fahre ich im Park Ski.",
        7: "Ich fahre regelmäßig im Park Ski",
        8: "Ich fahre regelmäßig im Park Ski",
        9: "Ich verbringe die meiste Zeit im Park!",
        10: "Ich verbringe die meiste Zeit im Park!",
      },
      "pl": {
        1: "Nigdy nie jeżdżę na nartach w parku rozrywki.",
        2: "Nigdy nie jeżdżę na nartach w parku rozrywki.",
        3: "Może spróbuję zjechać trasę w parku rozrywki.",
        4: "Może spróbuję zjechać trasę w parku rozrywki.",
        5: "Okazjonalnie jeżdżę na nartach w parku.",
        6: "Okazjonalnie jeżdżę na nartach w parku.",
        7: "Regularnie jeżdżę na nartach w parku",
        8: "Regularnie jeżdżę na nartach w parku",
        9: "Większość czasu spędzam w parku!",
        10: "Większość czasu spędzam w parku!",
      },
      "fr": {
        1: "Je ne fais jamais de ski dans le parc d'attractions.",
        2: "Je ne fais jamais de ski dans le parc d'attractions.",
        3: "Je pourrais essayer un tour dans le parc d'attractions.",
        4: "Je pourrais essayer un tour dans le parc d'attractions.",
        5: "Je fais occasionnellement du ski dans le parc.",
        6: "Je fais occasionnellement du ski dans le parc.",
        7: "Je fais régulièrement du ski dans le parc",
        8: "Je fais régulièrement du ski dans le parc",
        9: "Je passe la plupart de mon temps dans le parc !",
        10: "Je passe la plupart de mon temps dans le parc !",
      },
    },
    "playfull": {
      "en": {
        1: "I like high-performance skis!",
        2: "I like high-performance skis!",
        3: "I'm a strong, fast skier.",
        4: "I'm a strong, fast skier.",
        5: "I like a stable, forgiving ski.",
        6: "I like a stable, forgiving ski.",
        7: "I like a playful ski.",
        8: "I like a playful ski.",
        9: "I just butter and jump around!",
        10: "I just butter and jump around!",
      },
      "nl": {
        1: "Ik wil pittige, stijve skis!",
        2: "Ik wil pittige, stijve skis!",
        3: "Ik ben een sterke, snelle skiër.",
        4: "Ik ben een sterke, snelle skiër.",
        5: "Ik wil een stabiele ski.",
        6: "Ik wil een stabiele ski.",
        7: "Ik wil een speelse ski.",
        8: "Ik wil een speelse ski.",
        9: "Ik wil alleen maar springen!",
        10: "Ik wil alleen maar springen!",
      },
      "ja": {
        1: "ハイパフォーマンスなスキーが好きです！",
        2: "ハイパフォーマンスなスキーが好きです！",
        3: "私は強くて速いスキーヤーです。",
        4: "私は強くて速いスキーヤーです。",
        5: "安定して許容性のあるスキーが好きです。",
        6: "安定して許容性のあるスキーが好きです。",
        7: "遊び心のあるスキーが好きです。",
        8: "遊び心のあるスキーが好きです。",
        9: "バターしてジャンプするのが好きです！",
        10: "バターしてジャンプするのが好きです！",
      },
      "es": {
        1: "¡Me gustan los esquís de alto rendimiento!",
        2: "¡Me gustan los esquís de alto rendimiento!",
        3: "Soy un esquiador fuerte y rápido.",
        4: "Soy un esquiador fuerte y rápido.",
        5: "Me gustan los esquís estables y tolerantes.",
        6: "Me gustan los esquís estables y tolerantes.",
        7: "Me gustan los esquís juguetones.",
        8: "Me gustan los esquís juguetones.",
        9: "¡Solo me dedico a saltar y hacer maniobras!",
        10: "¡Solo me dedico a saltar y hacer maniobras!",
      },
      "de": {
        1: "Ich mag leistungsstarke Skier!",
        2: "Ich mag leistungsstarke Skier!",
        3: "Ich bin ein starker und schneller Skifahrer.",
        4: "Ich bin ein starker und schneller Skifahrer.",
        5: "Ich mag einen stabilen, verzeihenden Ski.",
        6: "Ich mag einen stabilen, verzeihenden Ski.",
        7: "Ich mag einen spielerischen Ski.",
        8: "Ich mag einen spielerischen Ski.",
        9: "Ich mache nur Butter und springe herum!",
        10: "Ich mache nur Butter und springe herum!",
      },
      "pl": {
        1: "Lubię wydajne narty!",
        2: "Lubię wydajne narty!",
        3: "Jestem silnym i szybkim narciarzem.",
        4: "Jestem silnym i szybkim narciarzem.",
        5: "Lubię stabilne i wyrozumiałe narty.",
        6: "Lubię stabilne i wyrozumiałe narty.",
        7: "Lubię zabawne narty.",
        8: "Lubię zabawne narty.",
        9: "Uwielbiam skakać i wykonywać triki!",
        10: "Uwielbiam skakać i wykonywać triki!",
      },
      "fr": {
        1: "J'aime les skis haute performance !",
        2: "J'aime les skis haute performance !",
        3: "Je suis un skieur rapide et fort.",
        4: "Je suis un skieur rapide et fort.",
        5: "J'aime un ski stable et indulgent.",
        6: "J'aime un ski stable et indulgent.",
        7: "J'aime un ski ludique.",
        8: "J'aime un ski ludique.",
        9: "Je me contente de faire des sauts et des figures !",
        10: "Je me contente de faire des sauts et des figures !",
      },
    },
  }
}

export default textsHome