const texts = {
    blogs: {
        en: "Blogs",
        nl: "Blogs",
        ja: "Blogs",
        pl: "Blogs",
        es: "Blogs",
        de: "Blogs",
        fr: "Blogs",
    },
    subscribeToNewsletter: {
        en: "Subscribe to our newsletter",
        nl: "Abonneer je op onze nieuwsbrief",
        ja: "ニュースレターに登録",
        pl: "Zapisz się do newslettera",
        es: "Suscríbete a nuestro boletín",
        de: "Abonnieren Sie unseren Newsletter",
        fr: "Abonnez-vous à notre newsletter",
    },
    newsletterDescription: {
        en: "Stay up-to-date on the latest ski releases and other ski related news. No intresting news? No newsletter!",
        nl: "Blijf op de hoogte van de nieuwste skireleases en ander ski-gerelateerd nieuws. Geen interessant nieuws? Geen nieuwsbrief!",
        ja: "最新のスキーリリースやその他のスキー関連ニュースを最新情報でご覧ください。興味深いニュースはありませんか？ ニュースレターはありません！",
        pl: "Bądź na bieżąco z najnowszymi wydawnictwami dotyczącymi nart i innych związanych z nimi wiadomościami. Brak ciekawych wiadomości? Brak newslettera!",
        es: "Manténgase al día con los últimos lanzamientos de esquí y otras noticias relacionadas con el esquí. ¿No hay noticias interesantes? ¡No hay boletín!",
        de: "Bleiben Sie auf dem Laufenden über die neuesten Ski-Veröffentlichungen und andere skirelevante Nachrichten. Keine interessanten Neuigkeiten? Kein Newsletter!",
        fr: "Restez au courant des dernières sorties de ski et autres nouvelles liées au ski. Pas de nouvelles intéressantes? Pas de newsletter!",
    },
    yourEmail: {
        en: "Enter your email",
        nl: "Voer uw e-mailadres in",
        ja: "メールアドレスを入力してください",
        pl: "Wprowadź swój adres e-mail",
        es: "Introduce tu correo electrónico",
        de: "Geben Sie Ihre E-Mail-Adresse ein",
        fr: "Entrez votre adresse e-mail",
    },
    subscribe: {
        en: "Subscribe",
        nl: "Abonneren",
        ja: "登録",
        pl: "Zapisz się",
        es: "Suscribir",
        de: "Abonnieren",
        fr: "S'abonner",
    },
    skiInfo: {
        en: "Ski Info",
        nl: "Ski Info",
        ja: "スキー情報",
        pl: "Informacje o nartach",
        es: "Información de esquí",
        de: "Ski Info",
        fr: "Info ski",
    },
    topPicks: {
        en: "Top picks",
        nl: "Top picks",
        ja: "おすすめ",
        pl: "Najlepsze wybory",
        es: "Selecciones principales",
        de: "Top-Auswahl",
        fr: "Meilleurs choix",
    },
    learnMore: {
        en: "Learn more",
        nl: "Lees meer",
        ja: "もっと詳しく",
        pl: "Dowiedz się więcej",
        es: "Aprende más",
        de: "Erfahren Sie mehr",
        fr: "En savoir plus",
    },
    aboutUs: {
        en: "About us",
        nl: "Over ons",
        ja: "私たちについて",
        pl: "O nas",
        es: "Sobre nosotros",
        de: "Über uns",
        fr: "À propos de nous",
    },
    opinions: {
        en: "Specs & opinions",
        nl: "Specs & meningen", 
        ja: "スペックと意見",
        pl: "Specyfikacje i opinie",
        es: "Especificaciones y opiniones",
        de: "Spezifikationen und Meinungen",
        fr: "Spécifications et opinions"
    },
    reviews: {
        en: "Reviews",
        nl: "Reviews",
        ja: "レビュー",
        pl: "Recenzje",
        es: "Reseñas",
        de: "Bewertungen",
        fr: "Avis"
    },
    articles: {
        en: "Articles",
        nl: "Artikelen",
        ja: "記事",
        pl: "Artykuły",
        es: "Artículos",
        de: "Artikel",
        fr: "Articles"
    },
    skiSelectionTool: {
        en: "Ski selection tool",
        nl: "Ski selectie tool",
        ja: "スキー選択ツール",
        pl: "Narzędzie do wyboru nart",
        es: "Herramienta de selección de esquís",
        de: "Ski-Auswahlwerkzeug",
        fr: "Outil de sélection de ski"
    },
    contact: {
        en: "Contact",
        nl: "Contact",
        ja: "接触",
        pl: "Kontakt",
        es: "Contacto",
        de: "Kontakt",
        fr: "Contact"
    },
    mission: {
        en: "Mission",
        nl: "Missie",
        ja: "ミッション",
        pl: "Misja",
        es: "Misión",
        de: "Mission",
        fr: "Mission"
    }

}

export default texts