const textsHome = {
  header: {
    "en": "Pick a ski",
    "nl": "Pick a ski",
  },
  title: {
    "en": "Ski Selector",
    "nl": "Ski Selector",
  },
  info: {
    "en": "Move the sliders around to find the right ski!",
    "nl": "Gebruik de sliders om de juiste skis te vinden!",
  },
  button: {
    "en": "Find skis!",
    "nl": "Skis zoeken!",
  },
  buttonLoading: {
    "en": "Loading...",
    "nl": "Laden...",
  },
  choicesTitle: {
    "en": "Your top ski choices.",
    "nl": "Onze ski suggesties.",
  },
  welcomeMessage: {
    "en": "Hi there!🙋‍♂️ This tool is brand new, i hope you enjoy it, and would love to hear your opinion!", 
    "nl": "Hey daar!🙋‍♂️ De tool is net nieuw, hopelijk ervaar je het als nuttig, ik ben erg benieuwd naar je mening!",
  },
  welcomeMessage2: {
    "en": "remco@pick-a-ski.com",
    "nl": "remco@pick-a-ski.com"
  },
  upperAlert1: {
    "en": "Welcome! The opinions page just launched, its a place where everybody can share their opinion about specific skis.🎊🎉",
    "nl": "Welkom! De meningen pagina is net gelanceerd, hier kan iedereen zijn of haar mening geven over een specifieke ski.🎊🎉",
  },
  upperAlert2: {
    "en": "Check to see if a you're intrested in is already in the list, if not send us a email and we will add it!",
    "nl": "Kijk of jou favoriete ski al in de lijst staat, zo niet stuur ons een email en we voegen hem toe!",
  },
  upperAlert3: {
    "en": "click here to visit the opinions page.",
    "nl": "klik hier om naar de meningen pagina te gaan.",
  },
  sliders: {
    "level": {
      "en": {
        1: "I never skied before.",
        2: "I never skied before.",
        3: "I've skied a couple of weeks.",
        4: "I've skied a couple of weeks.",
        5: "I ski 1-10 days a year.",
        6: "I ski 1-10 days a year.",
        7: "I ski multiple weeks every year.",
        8: "I ski multiple weeks every year.",
        9: "I live in the mountains!",
        10: "I live in the mountains!",
      },
      "nl": {
        1: "Ik heb nog nooit geskied.",
        2: "Ik heb nog nooit geskied.",
        3: "Ik heb een paar weken ervaring.",
        4: "Ik heb een paar weken ervaring.",
        5: "Ik ski 1-10 dagen per jaar.",
        6: "Ik ski 1-10 dagen per jaar.",
        7: "Ik ski een paar weken per jaar.",
        8: "Ik ski een paar weken per jaar.",
        9: "Ik leef in de bergen!",
        10: "Ik leef in de bergen!",
      },
    },
    "piste": {
      "en": {
        1: "I never ski on piste.",
        2: "I never ski on piste.",
        3: "I wont use this ski on piste.",
        4: "I wont use this ski on piste.",
        5: "I want it to be decent on piste.",
        6: "I want it to be decent on piste.",
        7: "I spend most days on piste.",
        8: "I spend most days on piste.",
        9: "Skiing slopes is my life!",
        10: "Skiing slopes is my life!",
      },
      "nl": {
        1: "Piste is niet belangrijk.",
        2: "Piste is niet belangrijk.",
        3: "Ik kom zelden op de piste.",
        4: "Ik kom zelden op de piste.",
        5: "Af en toe een rondje op de piste.",
        6: "Af en toe een rondje op de piste.",
        7: "Ik ben meestal op de piste.",
        8: "Ik ben meestal op de piste.",
        9: "Een ski speciaal voor de piste!",
        10: "Een ski speciaal voor de piste!",
      },
    },
    "powder": {
      "en": {
        1: "I never ski powder.",
        2: "I never ski powder.",
        3: "I like fresh snow on the slopes.",
        4: "I like fresh snow on the slopes.",
        5: "I like to ski between slopes",
        6: "I like to ski between slopes",
        7: "I like long powder runs",
        8: "I like long powder runs",
        9: "I travel for deep powder!",
        10: "I travel for deep powder!",
      },
      "nl": {
        1: "Ik ski nooit in de poeder.",
        2: "Ik ski nooit in de poeder.",
        3: "Poeder op de piste is leuk.",
        4: "Poeder op de piste is leuk.",
        5: "Ik ski wel eens tussen de pistes",
        6: "Ik ski wel eens tussen de pistes",
        7: "Ik doe graag lange poeder runs",
        8: "Ik doe graag lange poeder runs",
        9: "Ik wil alleen maar poederskiën!",
        10: "Ik wil alleen maar poederskiën!",
      },
    },
    "freeride": {
      "en": {
        1: "I dont care about freeride.",
        2: "I dont care about freeride.",
        3: "I like to ski trails in the forrest",
        4: "I like to ski trails in the forrest",
        5: "I occasionally go off-piste",
        6: "I occasionally go off-piste",
        7: "I'm often looking for cool lines",
        8: "I'm often looking for cool lines",
        9: "I ride freeride competitions!",
        10: "I ride freeride competitions!",
      },
      "nl": {
        1: "Freeriden is niets voor mij.",
        2: "Freeriden is niets voor mij.",
        3: "Ik pak af en toe wel een bospaadje.",
        4: "Ik pak af en toe wel een bospaadje.",
        5: "Ik ski wel eens buiten de piste.",
        6: "Ik ski wel eens buiten de piste.",
        7: "Vaak ben ik buiten de piste.",
        8: "Vaak ben ik buiten de piste.",
        9: "Ik ski freeride wedstrijden!",
        10: "Ik ski freeride wedstrijden!",
      },
    },
    "touring": {
      "en": {
        1: "I never go skitouring.",
        2: "I never go skitouring.",
        3: "I might try skitouring once.",
        4: "I might try skitouring once.",
        5: "I go touring once or twice",
        6: "I go touring once or twice",
        7: "I like skitouring regularly",
        8: "I like skitouring regularly",
        9: "Skitouring is all i do!",
        10: "Skitouring is all i do!",
      },
      "nl": {
        1: "Ik ga nooit skitouren.",
        2: "Ik ga nooit skitouren.",
        3: "Wellicht ga ik een keertje touren.",
        4: "Wellicht ga ik een keertje touren.",
        5: "Ik tour 1-2 keer per jaar.",
        6: "Ik tour 1-2 keer per jaar.",
        7: "Ik tour met enige regelmaat.",
        8: "Ik tour met enige regelmaat.",
        9: "Skitouren is het enige wat ik doe!",
        10: "Skitouren is het enige wat ik doe!",
      },

    },
    "park": {
      "en": {
        1: "I never ski in the funpark.",
        2: "I never ski in the funpark.",
        3: "I might try a funpark lap.",
        4: "I might try a funpark lap.",
        5: "I occasionally ride park.",
        6: "I occasionally ride park.",
        7: "I regularly ride park",
        8: "I regularly ride park",
        9: "I spend most time in the park!",
        10: "I spend most time in the park!",
      },
      "nl": {
        1: "Ik ski nooit in het funpark.",
        2: "Ik ski nooit in het funpark.",
        3: "Ik ga wel ooit park proberen.",
        4: "Ik ga wel ooit park proberen.",
        5: "Ik ski soms in het funpark.",
        6: "Ik ski soms in het funpark.",
        7: "Ik ski regelmatig funpark",
        8: "Ik ski regelmatig funpark",
        9: "Ik ben bijna altijd in het park!",
        10: "Ik ben bijna altijd in het park!",
      },
    },
    "playfull": {
      "en": {
        1: "I like high-performance ski's!",
        2: "I like high-performance ski's!",
        3: "I'm a strong, fast skier.",
        4: "I'm a strong, fast skier.",
        5: "I like a stable, forgiving ski.",
        6: "I like a stable, forgiving ski.",
        7: "I like a playfull ski.",
        8: "I like a playfull ski.",
        9: "I just butter and jump around!",
        10: "I just butter and jump around!",
      },
      "nl": {
        1: "Ik wil pittige, stijve skis!",
        2: "Ik wil pittige, stijve skis!",
        3: "Ik ben een sterke, snelle skier.",
        4: "Ik ben een sterke, snelle skier.",
        5: "Ik wil een stabiele, vergevingsgezinde ski.",
        6: "Ik wil een stabiele, vergevingsgezinde ski.",
        7: "Ik wil een speelse ski.",
        8: "Ik wil een speelse ski.",
        9: "Ik wil alleen maar springen en butteren!",
        10: "Ik wil alleen maar springen en butteren!",
      },
    }
  }
}

export default textsHome